FROM node:24-alpine3.21

WORKDIR /usr/src/app

RUN apk add --no-cache netcat-openbsd dos2unix

COPY package*.json ./
COPY prisma ./prisma

RUN npm install

RUN npm install -g @nestjs/cli

COPY . .

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN dos2unix /usr/local/bin/docker-entrypoint.sh && \ 
    chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT [ "docker-entrypoint.sh" ]


EXPOSE 3000
# EXPOSE 5555

CMD [ "npm", "run", "start:dev" ]
